2021-02-05 15:26:13,297 INFO    MainThread:177486 [wandb_setup.py:_flush():70] setting env: {}
2021-02-05 15:26:13,298 INFO    MainThread:177486 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-02-05 15:26:13,298 INFO    MainThread:177486 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-05 15:26:13,298 INFO    MainThread:177486 [wandb_init.py:_log_setup():318] Logging user logs to /home/enricalvove/Desktop/detr_facebook/detr/wandb/run-20210205_152613-35i0j3nl/logs/debug.log
2021-02-05 15:26:13,298 INFO    MainThread:177486 [wandb_init.py:_log_setup():319] Logging internal logs to /home/enricalvove/Desktop/detr_facebook/detr/wandb/run-20210205_152613-35i0j3nl/logs/debug-internal.log
2021-02-05 15:26:15,418 INFO    MainThread:177486 [wandb_run.py:_console_start():1399] atexit reg
2021-02-05 15:26:15,418 INFO    MainThread:177486 [wandb_run.py:_redirect():1262] redirect: SettingsConsole.REDIRECT
2021-02-05 15:26:15,418 INFO    MainThread:177486 [wandb_run.py:_redirect():1267] Redirecting console.
2021-02-05 15:26:15,418 INFO    MainThread:177486 [redirect.py:install():213] install start
2021-02-05 15:26:15,419 INFO    MainThread:177486 [redirect.py:install():228] install stop
2021-02-05 15:26:15,419 INFO    MainThread:177486 [redirect.py:install():213] install start
2021-02-05 15:26:15,419 INFO    MainThread:177486 [redirect.py:install():228] install stop
2021-02-05 15:26:15,419 INFO    MainThread:177486 [wandb_run.py:_redirect():1313] Redirects installed.
2021-02-05 16:14:23,885 INFO    MainThread:177486 [wandb_run.py:_atexit_cleanup():1369] got exitcode: 255
2021-02-05 16:14:23,885 INFO    MainThread:177486 [wandb_run.py:_restore():1341] restore
2021-02-05 16:14:23,885 INFO    MainThread:177486 [redirect.py:uninstall():232] uninstall start
2021-02-05 16:14:23,885 INFO    MainThread:177486 [redirect.py:_stop():287] _stop: stdout
2021-02-05 16:14:23,886 INFO    MainThread:177486 [redirect.py:_stop():293] _stop closed: stdout
2021-02-05 16:14:23,886 INFO    stdout    :177486 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2021-02-05 16:14:23,886 INFO    stdout    :177486 [redirect.py:_pipe_relay():145] relay done done: stdout
2021-02-05 16:14:23,886 INFO    MainThread:177486 [redirect.py:_stop():299] _stop joined: stdout
2021-02-05 16:14:23,886 INFO    MainThread:177486 [redirect.py:_stop():301] _stop rd closed: stdout
2021-02-05 16:14:23,886 INFO    MainThread:177486 [redirect.py:uninstall():236] uninstall done
2021-02-05 16:14:23,886 INFO    MainThread:177486 [redirect.py:uninstall():232] uninstall start
2021-02-05 16:14:23,886 INFO    MainThread:177486 [redirect.py:_stop():287] _stop: stderr
2021-02-05 16:14:23,886 INFO    MainThread:177486 [redirect.py:_stop():293] _stop closed: stderr
2021-02-05 16:14:23,886 INFO    stderr    :177486 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2021-02-05 16:14:23,886 INFO    stderr    :177486 [redirect.py:_pipe_relay():145] relay done done: stderr
2021-02-05 16:14:23,886 INFO    MainThread:177486 [redirect.py:_stop():299] _stop joined: stderr
2021-02-05 16:14:23,886 INFO    MainThread:177486 [redirect.py:_stop():301] _stop rd closed: stderr
2021-02-05 16:14:23,886 INFO    MainThread:177486 [redirect.py:uninstall():236] uninstall done
2021-02-05 16:14:24,155 INFO    MainThread:177486 [wandb_run.py:_wait_for_finish():1492] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 937
  total_bytes: 937
}

2021-02-05 16:14:26,161 INFO    MainThread:177486 [wandb_run.py:_wait_for_finish():1492] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1154749
  total_bytes: 1154749
}

2021-02-05 16:14:27,383 INFO    MainThread:177486 [wandb_run.py:_show_summary():1647] rendering summary
2021-02-05 16:14:27,383 INFO    MainThread:177486 [wandb_run.py:_show_history():1685] rendering history
2021-02-05 16:14:27,384 INFO    MainThread:177486 [wandb_run.py:_show_files():1714] logging synced files
2021-02-05 16:14:27,385 INFO    MainThread:177486 [internal.py:handle_exit():156] Internal process exited
